name: main

on:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge format
        run: |
          forge fmt --check
        id: format

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Solhint
        run: |
          npm install -g solhint
          solhint 'src/**/*.sol'
        id: lint
